apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets-operator
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.9
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
