apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
spec:
  destination:
    namespace: mongodb-operator
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: community-operator
    helm:
      parameters:
        - name: operator.watchNamespace
          value: "*"
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 0.7.5
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
