apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq-operator
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: rabbitmq-cluster-operator
    helm:
      {}
      # parameters:
      # - name: operator.watchNamespace
      #   value: "*"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.7.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
