apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kdrfc-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: kdrfc-gcp-connector
  target:
    name: kdrfc-common
    template:
      data:
        KDRFC__Account: "kdrfc-account.kdrfc.svc.cluster.local:8081"
        KDRFC__Stroage: "kdrfc-storage.kdrfc.svc.cluster.local:8082"
        KDRFC__Key: "{{ .symmetricKeys }}"

  data:
    - secretKey: symmetricKeys
      remoteRef:
        key: kdrfc-symmetric-keys
        decodingStrategy: None
