apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kdrfc-gcp-connector
spec:
  provider:
    gcpsm:
      projectID: realworld-cloud-study
      auth:
        workloadIdentity:
          clusterLocation: "asia-northeast3"
          clusterName: "realworld-cloud-study"
          clusterProjectID: realworld-cloud-study
          serviceAccountRef:
            name: "gcp-workload"
