apiVersion: v1
kind: Service
metadata:
  name: kdrfc-storage
spec:
  type: ClusterIP
  ports:
    - name: storage-service-port
      port: 8082
      targetPort: 80
  selector:
    app: storage-server
