apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kdrfc-gateway-rules
spec:
  hosts:
    - "*"
  gateways:
    - kdrfc-gateway
  http:
    - match:
      - uri:
          prefix: /api/accounts
      route:
        - destination:
            host: kdrfc-account-service
            port:
              number: 8081
