---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: kdrfc-database
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: kdrfc-database-password
      roles:
        - name: root
          db: admin
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-0
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: openebs-hostpath
            resources:
              requests:
                storage: 10G
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: openebs-hostpath
            resources:
              requests:
                storage: 1G
---
apiVersion: v1
kind: Secret
metadata:
  name: kdrfc-database-password
type: Opaque
stringData:
  password: asdfasdfasdf
