apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kdrfc-mongodb
  namespace: argocd
spec:
  destination:
    namespace: kdrfc
    server: https://kubernetes.default.svc
  project: kdrfc
  source:
    path: KDRFC-MongoDb
    repoURL: https://github.com/KangDroid-File-Cloud/KDRFC-K8s-Manifests.git
    targetRevision: test-server
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
