apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kdrfc-gateway
  namespace: argocd
spec:
  destination:
    namespace: kdrfc
    server: https://kubernetes.default.svc
  project: kdrfc
  source:
    path: "."
    repoURL: "https://github.com/KangDroid-File-Cloud/KDRFC-K8s-Gateway.git"
    targetRevision: main
