apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdrfc-account
spec:
  selector:
    matchLabels:
      app: account-server
  template:
    metadata:
      labels:
        app: account-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: account-server
          image: kangdroid.azurecr.io/account:d8076a5
          resources: {}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            httpGet:
              path: "/health"
              port: 80
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: kdrfc-common
          env:
            - name: Mongo__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: kdrfc-database-admin-admin
                  key: connectionString.standard
            - name: Mongo__DatabaseName
              value: Accounts
            - name: RabbitMq__Host
              valueFrom:
                secretKeyRef:
                  name: kdrfc-rabbitmq-default-user
                  key: host
            - name: RabbitMq__VirtualHost
              value: "/"
            - name: RabbitMq__UserName
              valueFrom:
                secretKeyRef:
                  name: kdrfc-rabbitmq-default-user
                  key: username
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: kdrfc-rabbitmq-default-user
                  key: password
