apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdrfc-account
spec:
  selector:
    matchLabels:
      app: account-server
  template:
    metadata:
      labels:
        app: account-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: account-server
          image: kangdroid.azurecr.io/account:31ace06
          resources: {}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            httpGet:
              path: "/health"
              port: 80
          ports:
            - containerPort: 80
          env:
            - name: Mongo__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: kdrfc-database-admin-admin
                  key: connectionString.standard
            - name: Mongo__DatabaseName
              value: Accounts
