apiVersion: v1
kind: Service
metadata:
  name: kdrfc-account
spec:
  type: ClusterIP
  ports:
    - name: account-service-port
      port: 8081
      targetPort: 80
  selector:
    app: account-server
